config-version: 2

name: 'zendesk_source'
version: '0.6.1'


require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  zendesk_source:
    materialized: view
    +schema: staging_zendesk
    tmp:
      materialized: view

vars:
  zendesk_source:
    group: "{{ source('bronze_zendesk', 'group') }}"
    brand: "{{ source('bronze_zendesk', 'brand') }}"
    domain_name: "{{ source('bronze_zendesk', 'domain_name') }}"
    organization_tag: "{{ source('bronze_zendesk', 'organization_tag') }}"
    organization: "{{ source('bronze_zendesk', 'organization') }}"
    schedule: "{{ source('bronze_zendesk', 'schedule') }}"
    satisfaction_rating: "{{ source('bronze_zendesk', 'satisfaction_rating') }}"
    ticket: "{{ source('bronze_zendesk', 'ticket') }}"
    ticket_form_history: "{{ source('bronze_zendesk', 'ticket_form_history') }}"
    ticket_comment: "{{ source('bronze_zendesk', 'ticket_comment') }}"
    ticket_field_history: "{{ source('bronze_zendesk', 'ticket_field_history') }}"
    ticket_schedule: "{{ source('bronze_zendesk', 'ticket_schedule') }}"
    ticket_tag: "{{ source('bronze_zendesk', 'ticket_tag') }}"
    user_tag: "{{ source('bronze_zendesk', 'user_tag') }}"
    user: "{{ source('bronze_zendesk', 'user') }}"
    time_zone: "{{ source('bronze_zendesk', 'time_zone') }}"
    daylight_time: "{{ source('bronze_zendesk', 'daylight_time') }}"
    zendesk_schema: bronze_zendesk
    using_schedules: false 
    zendesk__ticket_passthrough_columns: [
    'custom_received_at_noreply_'
    ,'custom_ticket_type'
    ,'custom_about'
    ,'custom_total_time_spent_sec_'
    , 'custom_qc_provided_accurate_information_asked_clarifying_question'
    , 'custom_qc_used_connection_empathy_statement_s_'
    , 'custom_qc_cobrowsed_with_a_customer'
    , 'custom_qc_validated_the_customer'
    , 'custom_qc_had_a_winback'
    , 'custom_qc_was_courteous_throughout_the_interaction'
    , 'custom_qc_accuracy_comments'
    , 'custom_qc_properly_documented_the_ticket'
    , 'custom_qc_provided_tip_best_practices'
    , 'custom_qc_followed_procedures'
    , 'custom_qc_connection_comments'
    , 'custom_qc_offered_opportunity_for_follow_up_questions'
    , 'custom_qc_has_been_qc_d'
    , 'custom_qc_included_product_penetration_statement'
    , 'custom_qc_security_comments'
    ]
