config-version: 2

name: 'zendesk_source'
version: '0.6.1'


require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  zendesk_source:
    materialized: table
    +schema: staging_zendesk
    tmp:
      materialized: view

vars:
  zendesk_source:
    group: "{{ source('bronze_zendesk', 'group') }}"
    brand: "{{ source('bronze_zendesk', 'brand') }}"
    domain_name: "{{ source('bronze_zendesk', 'domain_name') }}"
    organization_tag: "{{ source('bronze_zendesk', 'organization_tag') }}"
    organization: "{{ source('bronze_zendesk', 'organization') }}"
    schedule: "{{ source('bronze_zendesk', 'schedule') }}"
    satisfaction_rating: "{{ source('bronze_zendesk', 'satisfaction_rating') }}"
    ticket: "{{ source('bronze_zendesk', 'ticket') }}"
    ticket_form_history: "{{ source('bronze_zendesk', 'ticket_form_history') }}"
    ticket_comment: "{{ source('bronze_zendesk', 'ticket_comment') }}"
    ticket_field_history: "{{ source('bronze_zendesk', 'ticket_field_history') }}"
    ticket_schedule: "{{ source('bronze_zendesk', 'ticket_schedule') }}"
    ticket_tag: "{{ source('bronze_zendesk', 'ticket_tag') }}"
    user_tag: "{{ source('bronze_zendesk', 'user_tag') }}"
    user: "{{ source('bronze_zendesk', 'user') }}"
    time_zone: "{{ source('bronze_zendesk', 'time_zone') }}"
    daylight_time: "{{ source('bronze_zendesk', 'daylight_time') }}"
    zendesk_schema: bronze_zendesk
    using_schedules: false 
